namespace: sidecar-injector

resources:
- namespace.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- service.yaml
- serviceaccount.yaml
- configmap.yaml

images:
- name: sidecar-injector
  newName: docker.io/baghelg/sidecar-injector
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
